# Generated by Django 5.1.5 on 2025-04-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_class',
            field=models.TextField(default='', max_length=50),
        ),
    ]
